version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
